# Generated by Django 5.2.2 on 2025-06-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_moderatorgroup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModeratorGroup",
        ),
    ]
