# Generated by Django 5.2.2 on 2025-06-25 15:46

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_delete_moderatorgroup"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
