# Generated by Django 5.2.2 on 2025-06-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
    ]
